# Generated by Django 4.0.5 on 2022-06-08 07:58

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.utils.timezone import make_aware
from datetime import datetime


def run_seed(apps, _):
    User = apps.get_model("auth", "User")

    u1 = User(**{
        "password": make_password("rgarcia"),
        "is_superuser": True,
        "username": "rgarcia",
        "last_name": "Garcia",
        "email": "rgarcia@gmail.com",
        "is_staff": True,
        "is_active": True,
        "date_joined": make_aware(datetime(2022, 6, 3, 9, 0, 0)),
        "first_name": "Rodrigo",
    })
    u1.save()

    u2 = User(**{
        "password": make_password("cvilla"),
        "is_superuser": False,
        "username": "cvilla",
        "last_name": "Villa",
        "email": "cvilla@gmail.com",
        "is_staff": True,
        "is_active": True,
        "date_joined": make_aware(datetime(2022, 6, 4, 9, 0, 0)),
        "first_name": "Craig",
    })
    u2.save()

    u3 = User(**{
        "password": make_password("mellis"),
        "is_superuser": False,
        "username": "mellis",
        "last_name": "Ellis",
        "email": "mellis@gmail.com",
        "is_staff": True,
        "is_active": True,
        "date_joined": make_aware(datetime(2022, 6, 5, 9, 0, 0)),
        "first_name": "Monica",
    })
    u3.save()

    Channel = apps.get_model("core", "Channel")
    c1 = Channel(**{
        "name": "General",
        "description": "Generic conversations and messages",
        "created": make_aware(datetime(2022, 6, 4, 12, 0, 0)),
    })
    c1.save()
    c1.users.add(u1)
    c1.users.add(u2)

    c2 = Channel(**{
        "name": "Announcements",
        "description": "Important announcements for all audiences",
        "created": make_aware(datetime(2022, 6, 4, 12, 0, 0)),
    })
    c2.save()
    c2.users.add(u1)
    c2.users.add(u2)
    c2.users.add(u3)

    c3 = Channel(**{
        "name": "Random",
        "description": "For all the rest of things",
        "created": make_aware(datetime(2022, 6, 4, 12, 0, 0)),
    })
    c3.save()
    c3.users.add(u1)
    c3.users.add(u3)

    Message = apps.get_model("core", "Message")
    m1 = Message(**{
        "user": u1,
        "channel": c1,
        "content": "Welcome to the General channel",
        "created": make_aware(datetime(2022, 6, 4, 12, 0, 0)),
    })
    m1.save()

    m2 = Message(**{
        "user": u1,
        "channel": c2,
        "content": "Welcome to the Announcements channel",
        "created": make_aware(datetime(2022, 6, 4, 12, 0, 0)),
    })
    m2.save()

    m3 = Message(**{
        "user": u1,
        "channel": c3,
        "content": "Welcome to the Random channel",
        "created": make_aware(datetime(2022, 6, 4, 12, 0, 0)),
    })
    m3.save()

    m4 = Message(**{
        "user": u2,
        "channel": c1,
        "content": "How do I reset my password?",
        "created": make_aware(datetime(2022, 6, 6, 10, 0, 0)),
    })
    m4.save()

    m5 = Message(**{
        "user": u3,
        "channel": c2,
        "content": "Tomorrow the VPN will be down for maintenance reasons",
        "created": make_aware(datetime(2022, 6, 7, 15, 0, 0)),
    })
    m5.save()

    m6 = Message(**{
        "user": u2,
        "channel": c3,
        "content": "Any runners?",
        "created": make_aware(datetime(2022, 6, 8, 11, 0, 0)),
    })
    m6.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run_seed)
    ]
